externalDocs:
  description: pkg.go.dev
  url: https://pkg.go.dev/github.com/hsnice16/email-verifier@v0.2.1/core/service
info:
  contact: {}
paths:
  /health:
    get:
      responses:
        "200":
          description: OK
      summary: Health Check
      tags:
      - General
swagger: "2.0"
